version: '3.8'


services:

    mongo:
        image: mongo:latest
        hostname: mongo
        container_name: mongo
        environment:
            MONGO_INITDB_ROOT_USERNAME: user
            MONGO_INITDB_ROOT_PASSWORD: password
            MONGO_INITDB_DATABASE: database
        volumes:
            - type: volume
              source: ./mongo_data
              target: /data/db
        ports:
            - 27017:27017
        networks:
            - mongo_network

    mongo-express:
        image: mongo-express:latest
        hostname: mongo-express
        container_name: mongo-express
        environment:
            ME_CONFIG_MONGODB_ADMINUSERNAME: user
            ME_CONFIG_MONGODB_ADMINPASSWORD: password
            ME_CONFIG_MONGODB_PORT: 27017
            ME_CONFIG_MONGODB_SERVER: mongo
        ports:
            - 8081:8081
        networks:
            - mongo_network
        depends_on:
            - mongo


networks:

    mongo_network:
        driver: bridge


volumes:

    mongo_data:
