version: '3.8'


services:

  database_management_system:
    image: mongo:latest
    container_name: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: user
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: database
    volumes:
      - ./mongodb_data:/data/db
    ports:
      - 27017:27017
    networks:
      - production


networks:

  production:
    driver: bridge
