version: '3.8'


services:

    mongo_dbms:
        image: mongo:latest
        container_name: mongo_container
        environment:
            MONGO_INITDB_ROOT_USERNAME: user
            MONGO_INITDB_ROOT_PASSWORD: password
            MONGO_INITDB_DATABASE: database
        volumes:
            - type: volume
              source: ./mongodb_data
              target: /data/db
        ports:
            - 27017:27017
        networks:
            - mongodb_network

    mongo_gui:
        image: mongo-express:latest
        container_name: mongo-express_container
        environment:
            ME_CONFIG_MONGODB_ADMINUSERNAME: user
            ME_CONFIG_MONGODB_ADMINPASSWORD: password
            ME_CONFIG_MONGODB_PORT: 27017
            ME_CONFIG_MONGODB_SERVER: mongo_dbms
        ports:
            - 8081:8081
        networks:
            - mongodb_network
        depends_on:
            - mongo_dbms


networks:

    mongodb_network:
        driver: bridge


volumes:

    mongodb_data:
