version: '3.1'


services:

  database_management_system:
    image: postgres:latest
    container_name: postgresql
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: database
    volumes:
      - ./postgresql_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - production


networks:

  production:
    driver: bridge
