version: '3.8'


services:

    postgres:
        image: postgres:latest
        hostname: postgres
        container_name: postgres
        environment:
            POSTGRES_USER: user
            POSTGRES_PASSWORD: password
            POSTGRES_DB: database
        volumes:
            - type: volume
              source: ./postgres_data
              target: /var/lib/postgresql/data
        ports:
            - 5432:5432
        networks:
            - postgres_network

    pgweb:
        image: sosedoff/pgweb:latest
        hostname: pgweb
        container_name: pgweb
        environment:
            DATABASE_URL: postgres://user:password@postgres:5432/database?sslmode=disable
        ports:
            - 8081:8081
        networks:
            - postgres_network
        depends_on:
            - postgres


networks:

    postgres_network:
        driver: bridge


volumes:

    postgres_data:
